#pragma once

#define thread0_stage_index		(1)
#define mic_vc_stage_index		(5)
#define music_vc_stage_index		(6)
#define mic_vu_stage_index		(8)
#define peq_enable_stage_index		(10)
#define denoise_enable_stage_index		(13)
#define thread1_stage_index		(14)
#define reverb_stage_index		(16)
#define reverb_enable_stage_index		(17)
#define thread2_stage_index		(19)
#define duck0_enable_stage_index		(22)
#define duck1_enable_stage_index		(24)
#define thread3_stage_index		(27)
#define game_loopback_switch_ch0_stage_index		(30)
#define game_loopback_switch_ch1_stage_index		(31)
#define monitor_vc_stage_index		(32)
#define output_vc_stage_index		(33)
#define out_vu_stage_index		(35)
#define auto_thread_stage_indices  { thread0_stage_index, thread1_stage_index, thread2_stage_index, thread3_stage_index }
